payload:
#  - GEOSITE,category-ads-all
  - DOMAIN-SUFFIX,bigamybigot.space
  - DOMAIN-SUFFIX,magsrv.com
  - DOMAIN-SUFFIX,twlxxl.cn
  - DOMAIN-SUFFIX,glum-mortgage.com
  - DOMAIN-SUFFIX,registeridm.com
  - DOMAIN-SUFFIX,secure.internetdownloadmanager.com
#youtube去广告
  - DOMAIN-SUFFIX,2975c.v.fwmrm.net
  - DOMAIN-SUFFIX,2mdn.net
  - DOMAIN-SUFFIX,acquisition-tracker.wix.com
  - DOMAIN-SUFFIX,ad-emea.doubleclick.net
  - DOMAIN-SUFFIX,ad-g.doubleclick.net
  - DOMAIN-SUFFIX,ad.ae.doubleclick.net
  - DOMAIN-SUFFIX,ad.doubleclick.net
  - DOMAIN-SUFFIX,ad.jp.doubleclick.net
  - DOMAIN-SUFFIX,ad.n2434.doubleclick.net
  - DOMAIN-SUFFIX,ad.sg.doubleclick.net
  - DOMAIN-SUFFIX,ad.tw.doubleclick.net
  - DOMAIN-SUFFIX,ad.uk.doubleclick.net
  - DOMAIN-SUFFIX,ad.youtube.com
  - DOMAIN-SUFFIX,ad2.doubleclick.net
  - DOMAIN-SUFFIX,adclick.g.doubleclick.net
  - DOMAIN-SUFFIX,ade.googlesyndication.com
  - DOMAIN-SUFFIX,ads.doubleclick.net
  - DOMAIN-SUFFIX,ads.imeem.com
  - DOMAIN-SUFFIX,ads.youtube.com
  - DOMAIN-SUFFIX,adservice.google
  - DOMAIN-SUFFIX,akamaitechnologies.com
  - DOMAIN-SUFFIX,analytic-google.com
  - DOMAIN-SUFFIX,auto.search.msn.com
  - DOMAIN-SUFFIX,c.googlesyndication.com
  - DOMAIN-SUFFIX,cdn.fastclick.net
  - DOMAIN-SUFFIX,clients1.google.com
  - DOMAIN-SUFFIX,creative.cc-dt.com
  - DOMAIN-SUFFIX,doubleclick.de
  - DOMAIN-SUFFIX,doubleclick.net
  - DOMAIN-SUFFIX,dts.innovid.com
  - DOMAIN-SUFFIX,feedads.g.doubleclick.net
  - DOMAIN-SUFFIX,files.adform.net
  - DOMAIN-SUFFIX,fls.doubleclick.net
  - DOMAIN-SUFFIX,fwmrm.net
  - DOMAIN-SUFFIX,g.doubleclick.net
  - DOMAIN-SUFFIX,googleadapis.l.google.com
  - DOMAIN-SUFFIX,googleads.g.doubleclick.net
  - DOMAIN-SUFFIX,googleads2.g.doubleclick.net
  - DOMAIN-SUFFIX,googleads4.g.doubleclick.net
  - DOMAIN-SUFFIX,googleadservices.com
  - DOMAIN-SUFFIX,googletagmanager.com
  - DOMAIN-SUFFIX,i1.ytimg.com
  - DOMAIN-SUFFIX,innovid.com
  - DOMAIN-SUFFIX,iv.doubleclick.net
  - DOMAIN-SUFFIX,l.doubleclick.net
  - DOMAIN-SUFFIX,m.2mdn.net
  - DOMAIN-SUFFIX,m.doubleclick.net
  - DOMAIN-SUFFIX,m1.2mdn.net
  - DOMAIN-SUFFIX,media.fastclick.net
  - DOMAIN-SUFFIX,n4403ad.doubleclick.net
  - DOMAIN-SUFFIX,n479ad.doubleclick.net
  - DOMAIN-SUFFIX,ocsp.comodoca.com
  - DOMAIN-SUFFIX,pagead.googlesyndication.com
  - DOMAIN-SUFFIX,pagead.l.doubleclick.net
  - DOMAIN-SUFFIX,pagead1.googlesyndication.com
  - DOMAIN-SUFFIX,pagead2.googlesyndication.com
  - DOMAIN-SUFFIX,pagead46.googlesyndication.com
  - DOMAIN-SUFFIX,pixel.adsafeprotected.com
  - DOMAIN-SUFFIX,pixel.moatads.com
  - DOMAIN-SUFFIX,pubads.g.doubleclick.net
  - DOMAIN-SUFFIX,redirector.googlevideo.com
  - DOMAIN-SUFFIX,rtd.tubemogul.com
  - DOMAIN-SUFFIX,s.innovid.com
  - DOMAIN-SUFFIX,s.ytimg.com
  - DOMAIN-SUFFIX,s0.2mdn.net
  - DOMAIN-SUFFIX,s1.2mdn.net
  - DOMAIN-SUFFIX,secure-ds.serving-sys.com
  - DOMAIN-SUFFIX,securepubads.g.doubleclick.net
  - DOMAIN-SUFFIX,ssl.google-analytics.com
  - DOMAIN-SUFFIX,stat.livejournal.com
  - DOMAIN-SUFFIX,static.doubleclick.net
  - DOMAIN-SUFFIX,stats.g.doubleclick.net
  - DOMAIN-SUFFIX,tpc.googlesyndication.com
  - DOMAIN-SUFFIX,watchdog.goodbyeads
  - DOMAIN-SUFFIX,watchdog.goodbyeads.youtube
  - DOMAIN-SUFFIX,www-google-analytics.l.google.com
  - DOMAIN-SUFFIX,www-googletagmanager.l.google.com
  - DOMAIN-SUFFIX,www.analytic-google.com
  - DOMAIN-SUFFIX,www.googleadservices.com
  - DOMAIN-SUFFIX,www.googletagservices.com
  - DOMAIN-SUFFIX,yt.moatads.com
  - DOMAIN-SUFFIX,yt1.ggpht.com
  - DOMAIN-SUFFIX,yt10.ggpht.com
  - DOMAIN-SUFFIX,yt2.ggpht.com
  - DOMAIN-SUFFIX,yt2.ggpht.com
  - DOMAIN-SUFFIX,yt4.ggpht.com
  - DOMAIN-SUFFIX,yt5.ggpht.com
  - DOMAIN-SUFFIX,yt6.ggpht.com
  - DOMAIN-SUFFIX,yt7.ggpht.com
  - DOMAIN-SUFFIX,yt8.ggpht.com
  - DOMAIN-SUFFIX,yt9.ggpht.com
  - DOMAIN-SUFFIX,yts.moatads.com
  - DOMAIN-SUFFIX,yyz10s14-in-f14.1e100.net
  - DOMAIN-SUFFIX,notifications-pa.googleapis.com
#网易去广告
  - DOMAIN-SUFFIX,a.youdao.com
  - DOMAIN-SUFFIX,admusicpic.music.126.net
  - DOMAIN-SUFFIX,ads.music.126.net
  - DOMAIN-SUFFIX,analytics.163.com
  - DOMAIN-SUFFIX,crash.163.com
  - DOMAIN-SUFFIX,crashlytics.163.com
  - DOMAIN-SUFFIX,g.163.com
  - DOMAIN-SUFFIX,iadmat.nosdn.127.net
  - DOMAIN-SUFFIX,iadmatapk.nosdn.127.net
  - DOMAIN-SUFFIX,iadmusicmat.music.126.net
  - DOMAIN-SUFFIX,iadmusicmatvideo.music.126.net
  - DOMAIN-SUFFIX,sentry.music.163.com
  - DOMAIN-SUFFIX,yt-adp.ws.126.net
  - DOMAIN-SUFFIX,pg-ad-b1.ws.126.net
  - DOMAIN-SUFFIX,hongcai.163.com
  - DOMAIN-SUFFIX,lupic.cdn.bcebos.com
#新浪去广告
  - DOMAIN-SUFFIX,2016.sina.cn
  - DOMAIN-SUFFIX,ad.sina.com.cn
  - DOMAIN-SUFFIX,adbox.sina.com.cn
  - DOMAIN-SUFFIX,adimages.sina.com.hk
  - DOMAIN-SUFFIX,adimg.mobile.sina.cn
  - DOMAIN-SUFFIX,adimg.uve.weibo.com
  - DOMAIN-SUFFIX,adm.leju.sina.com.cn
  - DOMAIN-SUFFIX,ads.sina.com
  - DOMAIN-SUFFIX,alitui.weibo.com
  - DOMAIN-SUFFIX,api.apps.sina.cn
  - DOMAIN-SUFFIX,appgift.sinaapp.com
  - DOMAIN-SUFFIX,appsupdate.sinaapp.com
  - DOMAIN-SUFFIX,atm.sina.com
  - DOMAIN-SUFFIX,beacon.sina.com.cn
  - DOMAIN-SUFFIX,biz.weibo.com
  - DOMAIN-SUFFIX,click.uve.mobile.sina.cn
  - DOMAIN-SUFFIX,click.uve.weibo.com
  - DOMAIN-SUFFIX,contentrecommend-out.mobile.sina.cn
  - DOMAIN-SUFFIX,count.video.sina.com.cn
  - DOMAIN-SUFFIX,counter.sina.com.cn
  - DOMAIN-SUFFIX,cre.dp.sina.cn
  - DOMAIN-SUFFIX,cre-dp.sina.cn
  - DOMAIN-SUFFIX,d00.sina.com.cn
  - DOMAIN-SUFFIX,dcads.sina.com.cn
  - DOMAIN-SUFFIX,dl.kjava.sina.cn
  - DOMAIN-SUFFIX,dmp.sina.cn
  - DOMAIN-SUFFIX,dp.im.weibo.cn
  - DOMAIN-SUFFIX,game.weibo.cn
  - DOMAIN-SUFFIX,game.weibo.com
  - DOMAIN-SUFFIX,gw5.push.mcp.weibo.cn
  - DOMAIN-SUFFIX,gw6.push.mcp.weibo.cn
  - DOMAIN-SUFFIX,int.dpool.sina.com.cn
  - DOMAIN-SUFFIX,interest.mix.sina.com.cn
  - DOMAIN-SUFFIX,log.mix.sina.com.cn
  - DOMAIN-SUFFIX,log.sina.cn
  - DOMAIN-SUFFIX,mg.games.sina.com.cn
  - DOMAIN-SUFFIX,newspush.sinajs.cn
  - DOMAIN-SUFFIX,oascentral.sina.com
  - DOMAIN-SUFFIX,oascentral.sina.com.hk
  - DOMAIN-SUFFIX,p4p.sina.com.cn
  - DOMAIN-SUFFIX,palmnews.sina.cn
  - DOMAIN-SUFFIX,pay.mobile.sina.cn
  - DOMAIN-SUFFIX,pfp.sina.com.cn
  - DOMAIN-SUFFIX,pfpip.sina.com
  - DOMAIN-SUFFIX,promote.biz.weibo.cn
  - DOMAIN-SUFFIX,rm.sina.com.cn
  - DOMAIN-SUFFIX,rs.sinajs.cn
  - DOMAIN-SUFFIX,s.img.mix.sina.com.cn
  - DOMAIN-SUFFIX,sapi.sina.cn
  - DOMAIN-SUFFIX,sax.sina.cn
  - DOMAIN-SUFFIX,sax.sina.com.cn
  - DOMAIN-SUFFIX,saxn.sina.com.cn
  - DOMAIN-SUFFIX,saxs.sina.com.cn
  - DOMAIN-SUFFIX,sbeacon.sina.com.cn
  - DOMAIN-SUFFIX,sdkapp.mobile.sina.cn
  - DOMAIN-SUFFIX,sdkapp.uve.weibo.com
  - DOMAIN-SUFFIX,sdkclick.mobile.sina.cn
  - DOMAIN-SUFFIX,slog.sina.cn
  - DOMAIN-SUFFIX,slog.sina.com.cn
  - DOMAIN-SUFFIX,staticadm.leju.sina.com.cn
  - DOMAIN-SUFFIX,tjs.sjs.sinajs.cn
  - DOMAIN-SUFFIX,trends.mobile.sina.cn
  - DOMAIN-SUFFIX,u1.img.mobile.sina.cn
  - DOMAIN-SUFFIX,wapwbclick.mobile.sina.cn
  - DOMAIN-SUFFIX,wbapp.mobile.sina.cn
  - DOMAIN-SUFFIX,wbapp.uve.weibo.com
  - DOMAIN-SUFFIX,wbclick.mobile.sina.cn
  - DOMAIN-SUFFIX,wbpctips.mobile.sina.cn
  - DOMAIN-SUFFIX,widget.weibo.com
  - DOMAIN-SUFFIX,woocall.sina.com.cn
  - DOMAIN-SUFFIX,zymo.mps.weibo.com
#百度去广告
  - DOMAIN-SUFFIX,a.baidu.com
  - DOMAIN-SUFFIX,ad.duapps.com
  - DOMAIN-SUFFIX,ad.player.baidu.com
  - DOMAIN-SUFFIX,adm.baidu.com
  - DOMAIN-SUFFIX,adscdn.baidu.com
  - DOMAIN-SUFFIX,adx.xiaodutv.com
  - DOMAIN-SUFFIX,ae.bdstatic.com
  - DOMAIN-SUFFIX,afd.baidu.com
  - DOMAIN-SUFFIX,als.baidu.com
  - DOMAIN-SUFFIX,api.mobula.sdk.duapps.com
  - DOMAIN-SUFFIX,api.tuisong.baidu.com
  - DOMAIN-SUFFIX,appc.baidu.com
  - DOMAIN-SUFFIX,b.bdstatic.com
  - DOMAIN-SUFFIX,baichuan.baidu.com
  - DOMAIN-SUFFIX,baidustatic.com
  - DOMAIN-SUFFIX,baidutv.baidu.com
  - DOMAIN-SUFFIX,banlv.baidu.com
  - DOMAIN-SUFFIX,bar.baidu.com
  - DOMAIN-SUFFIX,bdplus.baidu.com
  - DOMAIN-SUFFIX,btlaunch.baidu.com
  - DOMAIN-SUFFIX,c.baidu.com
  - DOMAIN-SUFFIX,cb.baidu.com
  - DOMAIN-SUFFIX,cbjs.baidu.com
  - DOMAIN-SUFFIX,cjhq.baidu.com
  - DOMAIN-SUFFIX,cleaner.baidu.com
  - DOMAIN-SUFFIX,click.bes.baidu.com
  - DOMAIN-SUFFIX,click.qianqian.com
  - DOMAIN-SUFFIX,cm.baidu.com
  - DOMAIN-SUFFIX,cpro.baidu.cn
  - DOMAIN-SUFFIX,cpro.baidu.com
  - DOMAIN-SUFFIX,cpro.baidustatic.com
  - DOMAIN-SUFFIX,cpro.tieba.baidu.com
  - DOMAIN-SUFFIX,cpro.zhidao.baidu.com
  - DOMAIN-SUFFIX,cpro2.baidu.com
  - DOMAIN-SUFFIX,cpro2.baidustatic.com
  - DOMAIN-SUFFIX,cpu.baidu.com
  - DOMAIN-SUFFIX,crs.baidu.com
  - DOMAIN-SUFFIX,cstm.baidu.com
  - DOMAIN-SUFFIX,datax.baidu.com
  - DOMAIN-SUFFIX,dd713.bj.bcebos.com
  - DOMAIN-SUFFIX,dl.client.baidu.com
  - DOMAIN-SUFFIX,dl.ops.baidu.com
  - DOMAIN-SUFFIX,dl1sw.baidu.com
  - DOMAIN-SUFFIX,dl2.bav.baidu.com
  - DOMAIN-SUFFIX,dlsw.baidu.com
  - DOMAIN-SUFFIX,dlsw.br.baidu.com
  - DOMAIN-SUFFIX,dlswbr.baidu.com
  - DOMAIN-SUFFIX,dl-vip.bav.baidu.com
  - DOMAIN-SUFFIX,dl-vip.pcfaster.baidu.co.th
  - DOMAIN-SUFFIX,download.bav.baidu.com
  - DOMAIN-SUFFIX,download.sd.baidu.com
  - DOMAIN-SUFFIX,drmcmm.baidu.com
  - DOMAIN-SUFFIX,duiwai.baidu.com
  - DOMAIN-SUFFIX,dup.baidustatic.com
  - DOMAIN-SUFFIX,dxp.baidu.com
  - DOMAIN-SUFFIX,dzl.baidu.com
  - DOMAIN-SUFFIX,e.baidu.com
  - DOMAIN-SUFFIX,eclick.baidu.com
  - DOMAIN-SUFFIX,ecma.bdimg.com
  - DOMAIN-SUFFIX,ecmb.bdimg.com
  - DOMAIN-SUFFIX,ecmc.bdimg.com
  - DOMAIN-SUFFIX,eduad.baidu.com
  - DOMAIN-SUFFIX,eiv.baidu.com
  - DOMAIN-SUFFIX,em.baidu.com
  - DOMAIN-SUFFIX,entry.baidu.com
  - DOMAIN-SUFFIX,ers.baidu.com
  - DOMAIN-SUFFIX,f10.baidu.com
  - DOMAIN-SUFFIX,fc-feed.cdn.bcebos.com
  - DOMAIN-SUFFIX,fclick.baidu.com
  - DOMAIN-SUFFIX,fclog.baidu.com
  - DOMAIN-SUFFIX,feed.baidu.com
  - DOMAIN-SUFFIX,g.baidu.com
  - DOMAIN-SUFFIX,gimg.baidu.com
  - DOMAIN-SUFFIX,goutong.baidu.com
  - DOMAIN-SUFFIX,gsp1.baidu.com
  - DOMAIN-SUFFIX,guanjia.baidu.com
  - DOMAIN-SUFFIX,hao123union.baidu.com
  - DOMAIN-SUFFIX,hc.baidu.com
  - DOMAIN-SUFFIX,hm.baidu.com
  - DOMAIN-SUFFIX,hmma.baidu.com
  - DOMAIN-SUFFIX,hpd.baidu.com
  - DOMAIN-SUFFIX,idm.bce.baidu.com
  - DOMAIN-SUFFIX,idm-su.baidu.com
  - DOMAIN-SUFFIX,iebar.baidu.com
  - DOMAIN-SUFFIX,ikcode.baidu.com
  - DOMAIN-SUFFIX,img.taotaosou.cn
  - DOMAIN-SUFFIX,img01.taotaosou.cn
  - DOMAIN-SUFFIX,imgstat.baidu.com
  - DOMAIN-SUFFIX,iwanad.baidu.com
  - DOMAIN-SUFFIX,j.br.baidu.com
  - DOMAIN-SUFFIX,kstj.baidu.com
  - DOMAIN-SUFFIX,log.music.baidu.com
  - DOMAIN-SUFFIX,lxbjs.baidu.com
  - DOMAIN-SUFFIX,m1.baidu.com
  - DOMAIN-SUFFIX,ma.baidu.com
  - DOMAIN-SUFFIX,miao.baidu.com
  - DOMAIN-SUFFIX,mobads.baidu.com
  - DOMAIN-SUFFIX,mobads-logs.baidu.com
  - DOMAIN-SUFFIX,mpro.baidu.com
  - DOMAIN-SUFFIX,msite.baidu.com
  - DOMAIN-SUFFIX,neirong.baidu.com
  - DOMAIN-SUFFIX,nsclick.baidu.com
  - DOMAIN-SUFFIX,nsclickvideo.baidu.com
  - DOMAIN-SUFFIX,openrcv.baidu.com
  - DOMAIN-SUFFIX,pc.videoclick.baidu.com
  - DOMAIN-SUFFIX,pos.baidu.com
  - DOMAIN-SUFFIX,pups.bdimg.com
  - DOMAIN-SUFFIX,push.zhanzhang.baidu.com
  - DOMAIN-SUFFIX,qianclick.baidu.com
  - DOMAIN-SUFFIX,release.baidu.com
  - DOMAIN-SUFFIX,res.mi.baidu.com
  - DOMAIN-SUFFIX,rigel.baidustatic.com
  - DOMAIN-SUFFIX,river.zhidao.baidu.com
  - DOMAIN-SUFFIX,rj.baidu.com
  - DOMAIN-SUFFIX,rplog.baidu.com
  - DOMAIN-SUFFIX,s.baidu.com
  - DOMAIN-SUFFIX,sa.tuisong.baidu.com
  - DOMAIN-SUFFIX,sclick.baidu.com
  - DOMAIN-SUFFIX,sestat.baidu.com
  - DOMAIN-SUFFIX,shadu.baidu.com
  - DOMAIN-SUFFIX,share.baidu.com
  - DOMAIN-SUFFIX,sobar.baidu.com
  - DOMAIN-SUFFIX,sobartop.baidu.com
  - DOMAIN-SUFFIX,spcode.baidu.com
  - DOMAIN-SUFFIX,stat.v.baidu.com
  - DOMAIN-SUFFIX,su.bdimg.com
  - DOMAIN-SUFFIX,su.bdstatic.com
  - DOMAIN-SUFFIX,tk.baidu.com
  - DOMAIN-SUFFIX,tkweb.baidu.com
  - DOMAIN-SUFFIX,tob-cms.bj.bcebos.com
  - DOMAIN-SUFFIX,tongji.baidu.com
  - DOMAIN-SUFFIX,toolbar.baidu.com
  - DOMAIN-SUFFIX,tracker.baidu.com
  - DOMAIN-SUFFIX,tuijian.baidu.com
  - DOMAIN-SUFFIX,uat1.bfsspadserver.8le8le.com
  - DOMAIN-SUFFIX,ubmcmm.baidustatic.com
  - DOMAIN-SUFFIX,ucstat.baidu.com
  - DOMAIN-SUFFIX,ulic.baidu.com
  - DOMAIN-SUFFIX,ulog.imap.baidu.com
  - DOMAIN-SUFFIX,union.baidu.com
  - DOMAIN-SUFFIX,unionimage.baidu.com
  - DOMAIN-SUFFIX,utility.baidu.com
  - DOMAIN-SUFFIX,utk.baidu.com
  - DOMAIN-SUFFIX,videopush.baidu.com
  - DOMAIN-SUFFIX,vv84.bj.bcebos.com
  - DOMAIN-SUFFIX,w.gdown.baidu.com
  - DOMAIN-SUFFIX,w.x.baidu.com
  - DOMAIN-SUFFIX,wangmeng.baidu.com
  - DOMAIN-SUFFIX,weishi.baidu.com
  - DOMAIN-SUFFIX,wenku-cms.bj.bcebos.com
  - DOMAIN-SUFFIX,wisepush.video.baidu.com
  - DOMAIN-SUFFIX,wkctj.baidu.com
  - DOMAIN-SUFFIX,wm.baidu.com
  - DOMAIN-SUFFIX,znsv.baidu.com
  - DOMAIN-SUFFIX,zz.bdstatic.com
  - DOMAIN-SUFFIX,zzy1.quyaoya.com

####
