payload:
#  - GEOSITE,category-ads-all
  - DOMAIN-SUFFIX,bigamybigot.space
  - DOMAIN-SUFFIX,magsrv.com
  - DOMAIN-SUFFIX,twlxxl.cn
  - DOMAIN-SUFFIX,glum-mortgage.com
  - DOMAIN-SUFFIX,registeridm.com
  - DOMAIN-SUFFIX,secure.internetdownloadmanager.com
#youtube去广告
  - DOMAIN-SUFFIX,fonts.googleapis.com
  - DOMAIN-SUFFIX,fonts.gstatic.com
  - DOMAIN-SUFFIX,ads.youtube.com
  - DOMAIN-SUFFIX,clients1.google.com
  - DOMAIN-SUFFIX,pagead.googlesyndication.com
  - DOMAIN-SUFFIX,pagead1.googlesyndication.com
  - DOMAIN-SUFFIX,pagead2.googlesyndication.com
  - DOMAIN-SUFFIX,redirector.googlevideo.com
  - DOMAIN-SUFFIX,s.ytimg.com
  - DOMAIN-SUFFIX,yt3.googleusercontent.com
  - DOMAIN-SUFFIX,scooterxtreme.h5games.usercontent.goog
  - DOMAIN-SUFFIX,yt1.ggpht.com
  - DOMAIN-SUFFIX,yt10.ggpht.com
  - DOMAIN-SUFFIX,yt2.ggpht.com
  - DOMAIN-SUFFIX,yt3.ggpht.com
  - DOMAIN-SUFFIX,yt4.ggpht.com
  - DOMAIN-SUFFIX,yt5.ggpht.com
  - DOMAIN-SUFFIX,yt6.ggpht.com
  - DOMAIN-SUFFIX,yt7.ggpht.com
  - DOMAIN-SUFFIX,yt8.ggpht.com
  - DOMAIN-SUFFIX,yt9.ggpht.com
  - DOMAIN-SUFFIX,s.youtube.com
