payload:
  - DOMAIN-SUFFIX,bigamybigot.space
  - DOMAIN-SUFFIX,magsrv.com
  - DOMAIN-SUFFIX,twlxxl.cn
  - DOMAIN-SUFFIX,glum-mortgage.com
#https://github.com/ewpratten/youtube_ad_blocklist/blob/master/blocklist.txt
  - DOMAIN-SUFFIX,www.googletagservices.com
  - DOMAIN-SUFFIX,www-googletagmanager.l.google.com
  - DOMAIN-SUFFIX,www-google-analytics.l.google.com
  - DOMAIN-SUFFIX,www.googleadservices.com
  - DOMAIN-SUFFIX,www.analytic-google.com
  - DOMAIN-SUFFIX,tpc.googlesyndication.com
  - DOMAIN-SUFFIX,stats.g.doubleclick.net
  - DOMAIN-SUFFIX,static.doubleclick.net
  - DOMAIN-SUFFIX,ssl.google-analytics.com
  - DOMAIN-SUFFIX,s.innovid.com
  - DOMAIN-SUFFIX,securepubads.g.doubleclick.net
  - DOMAIN-SUFFIX,secure-ds.serving-sys.com
  - DOMAIN-SUFFIX,s0.2mdn.net
  - DOMAIN-SUFFIX,rtd.tubemogul.com
  - DOMAIN-SUFFIX,pubads.g.doubleclick.net
  - DOMAIN-SUFFIX,pixel.moatads.com
  - DOMAIN-SUFFIX,pagead.l.doubleclick.net
  - DOMAIN-SUFFIX,pagead.googlesyndication.com
  - DOMAIN-SUFFIX,pagead2.googlesyndication.com
  - DOMAIN-SUFFIX,pagead1.googlesyndication.com
  - DOMAIN-SUFFIX,innovid.com
  - DOMAIN-SUFFIX,googleads.g.doubleclick.net
  - DOMAIN-SUFFIX,googleadservices.com
  - DOMAIN-SUFFIX,googleads4.g.doubleclick.net
  - DOMAIN-SUFFIX,googleadapis.l.google.com
  - DOMAIN-SUFFIX,g.doubleclick.net
  - DOMAIN-SUFFIX,fwmrm.net
  - DOMAIN-SUFFIX,fls.doubleclick.net
  - DOMAIN-SUFFIX,files.adform.net
  - DOMAIN-SUFFIX,dts.innovid.com
  - DOMAIN-SUFFIX,doubleclick.net
  - DOMAIN-SUFFIX,analytic-google.com
  - DOMAIN-SUFFIX,ad.youtube.com
  - DOMAIN-SUFFIX,ads.youtube.com
  - DOMAIN-SUFFIX,adservice.google.com
  - DOMAIN-SUFFIX,ads.doubleclick.net
  - DOMAIN-SUFFIX,ad.mo.doubleclick.net
  - DOMAIN-SUFFIX,ad-g.doubleclick.net
  - DOMAIN-SUFFIX,ad.doubleclick.net
  - DOMAIN-SUFFIX,2mdn.net
  - DOMAIN-SUFFIX,2975c.v.fwmrm.net
  - DOMAIN-SUFFIX,rr3---sn-npoeenll.googlevideo.com
  - DOMAIN-SUFFIX,rr3---sn-npoeenly.googlevideo.com
  - DOMAIN-SUFFIX,rr1---sn-npoe7nz7.googlevideo.com
  - DOMAIN-SUFFIX,rr2---sn-oguesnd7.googlevideo.com
  - DOMAIN-SUFFIX,rr2---sn-3pm7knel.googlevideo.com
  - DOMAIN-SUFFIX,rr4---sn-3pm7kne7.googlevideo.com
  - DOMAIN-SUFFIX,rr1---sn-oguelnlz.googlevideo.com
  - DOMAIN-SUFFIX,rr4---sn-oguelnl7.googlevideo.com
  - DOMAIN-SUFFIX,rr4---sn-oguelner.googlevideo.com
  - DOMAIN-SUFFIX,rr4---sn-npoeener.googlevideo.com
  - DOMAIN-SUFFIX,rr4---sn-nx5s7n7y.googlevideo.com
  - DOMAIN-SUFFIX,rr1---sn-ab5sznze.googlevideo.com
  - DOMAIN-SUFFIX,rr1---sn-ab5l6nkd.googlevideo.com
  - DOMAIN-SUFFIX,rr4---sn-n4v7snll.googlevideo.com
  - DOMAIN-SUFFIX,rr2---sn-nx5s7n7s.googlevideo.com
  - DOMAIN-SUFFIX,rr2---sn-a5mlrnlz.googlevideo.com
