payload:
  - GEOSITE,category-ads-all
  - DOMAIN-SUFFIX,bigamybigot.space
  - DOMAIN-SUFFIX,magsrv.com
  - DOMAIN-SUFFIX,twlxxl.cn
  - DOMAIN-SUFFIX,glum-mortgage.com
  - DOMAIN-SUFFIX,registeridm.com
