payload:
#  - GEOSITE,category-ads-all
  - DOMAIN-SUFFIX,bigamybigot.space
  - DOMAIN-SUFFIX,magsrv.com
  - DOMAIN-SUFFIX,twlxxl.cn
  - DOMAIN-SUFFIX,glum-mortgage.com
  - DOMAIN-SUFFIX,registeridm.com
  - DOMAIN-SUFFIX,secure.internetdownloadmanager.com
#youtube去广告
  - DOMAIN-SUFFIX,fonts.googleapis.com
#  - DOMAIN-SUFFIX,fonts.gstatic.com
  - DOMAIN-SUFFIX,ads.youtube.com
  - DOMAIN-SUFFIX,clients1.google.com
  - DOMAIN-SUFFIX,pagead.googlesyndication.com
  - DOMAIN-SUFFIX,pagead1.googlesyndication.com
  - DOMAIN-SUFFIX,pagead2.googlesyndication.com
  - DOMAIN-SUFFIX,redirector.googlevideo.com
  - DOMAIN-SUFFIX,s.ytimg.com
  - DOMAIN-SUFFIX,yt3.googleusercontent.com
  - DOMAIN-SUFFIX,doubleclick.net
  - DOMAIN-SUFFIX,googleadservices.com
  - DOMAIN-SUFFIX,ade.googlesyndication.com
  - DOMAIN-SUFFIX,ad.youtube.com
  - DOMAIN-SUFFIX,clients4.google.com
