payload:
#  - GEOSITE,category-ads-all
  - DOMAIN-SUFFIX,bigamybigot.space
  - DOMAIN-SUFFIX,magsrv.com
  - DOMAIN-SUFFIX,twlxxl.cn
  - DOMAIN-SUFFIX,glum-mortgage.com
  - DOMAIN-SUFFIX,registeridm.com
  - DOMAIN-SUFFIX,secure.internetdownloadmanager.com
#youtube去广告
  - DOMAIN-SUFFIX,2975c.v.fwmrm.net
  - DOMAIN-SUFFIX,2mdn.net
  - DOMAIN-SUFFIX,acquisition-tracker.wix.com
  - DOMAIN-SUFFIX,ad-emea.doubleclick.net
  - DOMAIN-SUFFIX,ad-g.doubleclick.net
  - DOMAIN-SUFFIX,ad.ae.doubleclick.net
  - DOMAIN-SUFFIX,ad.doubleclick.net
  - DOMAIN-SUFFIX,ad.jp.doubleclick.net
  - DOMAIN-SUFFIX,ad.n2434.doubleclick.net
  - DOMAIN-SUFFIX,ad.sg.doubleclick.net
  - DOMAIN-SUFFIX,ad.tw.doubleclick.net
  - DOMAIN-SUFFIX,ad.uk.doubleclick.net
  - DOMAIN-SUFFIX,ad.youtube.com
  - DOMAIN-SUFFIX,ad2.doubleclick.net
  - DOMAIN-SUFFIX,adclick.g.doubleclick.net
  - DOMAIN-SUFFIX,ade.googlesyndication.com
  - DOMAIN-SUFFIX,ads.doubleclick.net
  - DOMAIN-SUFFIX,ads.imeem.com
  - DOMAIN-SUFFIX,ads.youtube.com
  - DOMAIN-SUFFIX,s.youtube.com
  - DOMAIN-SUFFIX,adservice.google
  - DOMAIN-SUFFIX,akamaitechnologies.com
  - DOMAIN-SUFFIX,analytic-google.com
  - DOMAIN-SUFFIX,c.googlesyndication.com
  - DOMAIN-SUFFIX,cdn.fastclick.net
  - DOMAIN-SUFFIX,clients1.google.com
  - DOMAIN-SUFFIX,creative.cc-dt.com
  - DOMAIN-SUFFIX,doubleclick.de
  - DOMAIN-SUFFIX,doubleclick.net
  - DOMAIN-SUFFIX,dts.innovid.com
  - DOMAIN-SUFFIX,feedads.g.doubleclick.net
  - DOMAIN-SUFFIX,files.adform.net
  - DOMAIN-SUFFIX,fls.doubleclick.net
  - DOMAIN-SUFFIX,fwmrm.net
  - DOMAIN-SUFFIX,g.doubleclick.net
  - DOMAIN-SUFFIX,googleadapis.l.google.com
  - DOMAIN-SUFFIX,googleads.g.doubleclick.net
  - DOMAIN-SUFFIX,googleads2.g.doubleclick.net
  - DOMAIN-SUFFIX,googleads4.g.doubleclick.net
  - DOMAIN-SUFFIX,googleadservices.com
  - DOMAIN-SUFFIX,googletagmanager.com
  - DOMAIN-SUFFIX,i1.ytimg.com
  - DOMAIN-SUFFIX,innovid.com
  - DOMAIN-SUFFIX,iv.doubleclick.net
  - DOMAIN-SUFFIX,l.doubleclick.net
  - DOMAIN-SUFFIX,m.2mdn.net
  - DOMAIN-SUFFIX,m.doubleclick.net
  - DOMAIN-SUFFIX,m1.2mdn.net
  - DOMAIN-SUFFIX,media.fastclick.net
  - DOMAIN-SUFFIX,n4403ad.doubleclick.net
  - DOMAIN-SUFFIX,n479ad.doubleclick.net
  - DOMAIN-SUFFIX,ocsp.comodoca.com
  - DOMAIN-SUFFIX,pagead.googlesyndication.com
  - DOMAIN-SUFFIX,pagead.l.doubleclick.net
  - DOMAIN-SUFFIX,pagead1.googlesyndication.com
  - DOMAIN-SUFFIX,pagead2.googlesyndication.com
  - DOMAIN-SUFFIX,pagead46.googlesyndication.com
  - DOMAIN-SUFFIX,pixel.adsafeprotected.com
  - DOMAIN-SUFFIX,pixel.moatads.com
  - DOMAIN-SUFFIX,pubads.g.doubleclick.net
  - DOMAIN-SUFFIX,redirector.googlevideo.com
  - DOMAIN-SUFFIX,rtd.tubemogul.com
  - DOMAIN-SUFFIX,s.innovid.com
  - DOMAIN-SUFFIX,s.ytimg.com
  - DOMAIN-SUFFIX,s0.2mdn.net
  - DOMAIN-SUFFIX,s1.2mdn.net
  - DOMAIN-SUFFIX,secure-ds.serving-sys.com
  - DOMAIN-SUFFIX,securepubads.g.doubleclick.net
  - DOMAIN-SUFFIX,ssl.google-analytics.com
  - DOMAIN-SUFFIX,stat.livejournal.com
  - DOMAIN-SUFFIX,static.doubleclick.net
  - DOMAIN-SUFFIX,stats.g.doubleclick.net
  - DOMAIN-SUFFIX,tpc.googlesyndication.com
  - DOMAIN-SUFFIX,watchdog.goodbyeads
  - DOMAIN-SUFFIX,watchdog.goodbyeads.youtube
  - DOMAIN-SUFFIX,www-google-analytics.l.google.com
  - DOMAIN-SUFFIX,www-googletagmanager.l.google.com
  - DOMAIN-SUFFIX,www.analytic-google.com
  - DOMAIN-SUFFIX,www.googleadservices.com
  - DOMAIN-SUFFIX,www.googletagservices.com
  - DOMAIN-SUFFIX,yt.moatads.com
  - DOMAIN-SUFFIX,yt1.ggpht.com
  - DOMAIN-SUFFIX,yt10.ggpht.com
  - DOMAIN-SUFFIX,yt2.ggpht.com
  - DOMAIN-SUFFIX,yt2.ggpht.com
  - DOMAIN-SUFFIX,yt4.ggpht.com
  - DOMAIN-SUFFIX,yt5.ggpht.com
  - DOMAIN-SUFFIX,yt6.ggpht.com
  - DOMAIN-SUFFIX,yt7.ggpht.com
  - DOMAIN-SUFFIX,yt8.ggpht.com
  - DOMAIN-SUFFIX,yt9.ggpht.com
  - DOMAIN-SUFFIX,yts.moatads.com
  - DOMAIN-SUFFIX,yyz10s14-in-f14.1e100.net
  - DOMAIN-SUFFIX,notifications-pa.googleapis.com
