payload:
#  - GEOSITE,category-ads-all
  - DOMAIN-SUFFIX,bigamybigot.space
  - DOMAIN-SUFFIX,magsrv.com
  - DOMAIN-SUFFIX,twlxxl.cn
  - DOMAIN-SUFFIX,glum-mortgage.com
  - DOMAIN-SUFFIX,registeridm.com
  - DOMAIN-SUFFIX,secure.internetdownloadmanager.com
#youtube去广告
  - DOMAIN-SUFFIX,ade.googlesyndication.com
  - DOMAIN-SUFFIX,pagead.googlesyndication.com
  - DOMAIN-SUFFIX,pagead1.googlesyndication.com
  - DOMAIN-SUFFIX,pagead2.googlesyndication.com
  - DOMAIN-SUFFIX,tpc.googlesyndication.com
  - DOMAIN-SUFFIX,ad.doubleclick.net
  - DOMAIN-SUFFIX,waa-pa.clients6.google.com
  - DOMAIN-SUFFIX,tpc.googlesyndication.com
  - DOMAIN-SUFFIX,googleads.g.doubleclick.net
  - DOMAIN-SUFFIX,playatoms-pa.googleapis.com
  - DOMAIN-SUFFIX,7f077.v.fwmrm.net
  - DOMAIN-SUFFIX,infinity-c39.youboranqs01.com
  - DOMAIN-SUFFIX,beacons.gcp.gvt2.com
  - DOMAIN-SUFFIX,beacons.gvt2.com
  - DOMAIN-SUFFIX,notifications-pa.googleapis.com
  - DOMAIN-SUFFIX,geller-pa.googleapis.com
  - DOMAIN-SUFFIX,semanticlocation-pa.googleapis.com
  - DOMAIN-SUFFIX,voilatile-pa.googleapis.com
  - DOMAIN-SUFFIX,play-fe.googleapis.com
  - DOMAIN-SUFFIX,androidpay-users-pa.googleapis.com
  - DOMAIN-SUFFIX,digitalassetlinks.googleapis.com
  - DOMAIN-SUFFIX,geomobileservices-pa.googleapis.com
  - DOMAIN-SUFFIX,finance-pa.googleapis.com
  - DOMAIN-SUFFIX,proactivebackend-pa.googleapis.com
  - DOMAIN-SUFFIX,searchnotifications-pa.googleapis.com
  - DOMAIN-SUFFIX,clientservices.googleapis.com
  - DOMAIN-SUFFIX,www.googleadservices.com
  - DOMAIN-SUFFIX,nearbysharing-pa.googleapis.com
  - DOMAIN-SUFFIX,firebaseinstallations.googleapis.com
  - DOMAIN-SUFFIX,static.doubleclick.net
  - DOMAIN-SUFFIX,encrypted-tbn1.gstatic.com
  - DOMAIN-SUFFIX,encrypted-tbn3.gstatic.com
  - DOMAIN-SUFFIX,encrypted-tbn0.gstatic.com
  - DOMAIN-SUFFIX,ssl.google-analytics.com
  - DOMAIN-SUFFIX,c.pki.goog
  - DOMAIN-SUFFIX,wpad.openwrt
  - DOMAIN-SUFFIX,dailysolitaire.h5games.usercontent.goog
  - DOMAIN-SUFFIX,ads.youtube.com
  - DOMAIN-SUFFIX,hoisin.ptskysrt.gitv.tv
  - DOMAIN-SUFFIX,redirector.googlevideo.com
  - DOMAIN-SUFFIX,s.ytimg.com
  - DOMAIN-SUFFIX,stun.l.google.com
  - DOMAIN-SUFFIX,ad.youtube.com
  - DOMAIN-SUFFIX,clients0.google.com
  - DOMAIN-SUFFIX,clients1.google.com
  - DOMAIN-SUFFIX,clients2.google.com
  - DOMAIN-SUFFIX,clients3.google.com
  - DOMAIN-SUFFIX,clients4.google.com
  - DOMAIN-SUFFIX,clients5.google.com
  - DOMAIN-SUFFIX,clients6.google.com
  - DOMAIN-SUFFIX,clients7.google.com
  - DOMAIN-SUFFIX,clients8.google.com
  - DOMAIN-SUFFIX,clients9.google.com
  - DOMAIN-SUFFIX,yt0.googleusercontent.com
  - DOMAIN-SUFFIX,yt1.googleusercontent.com
  - DOMAIN-SUFFIX,yt2.googleusercontent.com
  - DOMAIN-SUFFIX,yt3.googleusercontent.com
  - DOMAIN-SUFFIX,yt4.googleusercontent.com
  - DOMAIN-SUFFIX,yt5.googleusercontent.com
  - DOMAIN-SUFFIX,yt6.googleusercontent.com
  - DOMAIN-SUFFIX,yt7.googleusercontent.com
  - DOMAIN-SUFFIX,yt8.googleusercontent.com
  - DOMAIN-SUFFIX,yt9.googleusercontent.com
  - DOMAIN-SUFFIX,lh0.googleusercontent.com
  - DOMAIN-SUFFIX,lh1.googleusercontent.com
  - DOMAIN-SUFFIX,lh2.googleusercontent.com
  - DOMAIN-SUFFIX,lh3.googleusercontent.com
  - DOMAIN-SUFFIX,lh4.googleusercontent.com
  - DOMAIN-SUFFIX,lh5.googleusercontent.com
  - DOMAIN-SUFFIX,lh6.googleusercontent.com
  - DOMAIN-SUFFIX,lh7.googleusercontent.com
  - DOMAIN-SUFFIX,lh8.googleusercontent.com
  - DOMAIN-SUFFIX,lh9.googleusercontent.com
