payload:
  - DOMAIN-SUFFIX,bigamybigot.space
  - DOMAIN-SUFFIX,magsrv.com
  - DOMAIN-SUFFIX,twlxxl.cn
  - DOMAIN-SUFFIX,glum-mortgage.com
  - DOMAIN-SUFFIX,registeridm.com
  - DOMAIN,yt-adp.ws.126.net
  - DOMAIN-SUFFIX,hongcai.163.com
  - DOMAIN-SUFFIX,secure.internetdownloadmanager.com
  - DOMAIN-SUFFIX,lupic.cdn.bcebos.com
#  - GEOSITE,category-ads-all
