payload:
  - DOMAIN-SUFFIX,bigamybigot.space
  - DOMAIN-SUFFIX,magsrv.com
  - DOMAIN-SUFFIX,twlxxl.cn
  - DOMAIN-SUFFIX,glum-mortgage.com
  - DOMAIN-SUFFIX,registeridm.com
  - DOMAIN-SUFFIX,nstool.netease.com
  - DOMAIN-SUFFIX,crash.163.com
  - DOMAIN-SUFFIX,ac.dun.163.com
  - DOMAIN-SUFFIX,ac.dun.163yun.com
  - DOMAIN-SUFFIX,fp-upload.dun.163.com
  - DOMAIN-SUFFIX,factor.reg.163.com
  - DOMAIN-SUFFIX,sd-gl.xinqiucc.com
  - DOMAIN-SUFFIX,126.net
