payload:
#  - GEOSITE,category-ads-all
  - DOMAIN-SUFFIX,bigamybigot.space
  - DOMAIN-SUFFIX,magsrv.com
  - DOMAIN-SUFFIX,twlxxl.cn
  - DOMAIN-SUFFIX,glum-mortgage.com
  - DOMAIN-SUFFIX,registeridm.com
  - DOMAIN-SUFFIX,secure.internetdownloadmanager.com
#youtube去广告
  - DOMAIN-SUFFIX,fonts.googleapis.com
  - DOMAIN-SUFFIX,fonts.gstatic.com
  - DOMAIN-SUFFIX,ad-emea.doubleclick.net
  - DOMAIN-SUFFIX,ad-g.doubleclick.net
  - DOMAIN-SUFFIX,ad.ae.doubleclick.net
  - DOMAIN-SUFFIX,ad.doubleclick.net
  - DOMAIN-SUFFIX,ad.jp.doubleclick.net
  - DOMAIN-SUFFIX,ad.n2434.doubleclick.net
  - DOMAIN-SUFFIX,ad.sg.doubleclick.net
  - DOMAIN-SUFFIX,ad.tw.doubleclick.net
  - DOMAIN-SUFFIX,ad.uk.doubleclick.net
  - DOMAIN-SUFFIX,ad.youtube.com
  - DOMAIN-SUFFIX,ad2.doubleclick.net
  - DOMAIN-SUFFIX,adclick.g.doubleclick.net
  - DOMAIN-SUFFIX,ade.googlesyndication.com
  - DOMAIN-SUFFIX,ads.doubleclick.net
  - DOMAIN-SUFFIX,ads.youtube.com
  - DOMAIN-SUFFIX,s.youtube.com
  - DOMAIN-SUFFIX,adservice.google
  - DOMAIN-SUFFIX,analytic-google.com
  - DOMAIN-SUFFIX,c.googlesyndication.com
  - DOMAIN-SUFFIX,clients1.google.com
  - DOMAIN-SUFFIX,doubleclick.de
  - DOMAIN-SUFFIX,doubleclick.net
  - DOMAIN-SUFFIX,feedads.g.doubleclick.net
  - DOMAIN-SUFFIX,fls.doubleclick.net
  - DOMAIN-SUFFIX,g.doubleclick.net
  - DOMAIN-SUFFIX,googleadapis.l.google.com
  - DOMAIN-SUFFIX,googleads.g.doubleclick.net
  - DOMAIN-SUFFIX,googleads2.g.doubleclick.net
  - DOMAIN-SUFFIX,googleads4.g.doubleclick.net
  - DOMAIN-SUFFIX,googleadservices.com
  - DOMAIN-SUFFIX,googletagmanager.com
  - DOMAIN-SUFFIX,i1.ytimg.com
  - DOMAIN-SUFFIX,i9.ytimg.com 
  - DOMAIN-SUFFIX,innovid.com
  - DOMAIN-SUFFIX,iv.doubleclick.net
  - DOMAIN-SUFFIX,l.doubleclick.net
  - DOMAIN-SUFFIX,m.doubleclick.net
  - DOMAIN-SUFFIX,n4403ad.doubleclick.net
  - DOMAIN-SUFFIX,n479ad.doubleclick.net
  - DOMAIN-SUFFIX,pagead.googlesyndication.com
  - DOMAIN-SUFFIX,pagead.l.doubleclick.net
  - DOMAIN-SUFFIX,pagead1.googlesyndication.com
  - DOMAIN-SUFFIX,pagead2.googlesyndication.com
  - DOMAIN-SUFFIX,pagead46.googlesyndication.com
  - DOMAIN-SUFFIX,pubads.g.doubleclick.net
  - DOMAIN-SUFFIX,redirector.googlevideo.com
  - DOMAIN-SUFFIX,s.ytimg.com
  - DOMAIN-SUFFIX,securepubads.g.doubleclick.net
  - DOMAIN-SUFFIX,ssl.google-analytics.com
  - DOMAIN-SUFFIX,static.doubleclick.net
  - DOMAIN-SUFFIX,stats.g.doubleclick.net
  - DOMAIN-SUFFIX,tpc.googlesyndication.com
  - DOMAIN-SUFFIX,www-google-analytics.l.google.com
  - DOMAIN-SUFFIX,www-googletagmanager.l.google.com
  - DOMAIN-SUFFIX,www.analytic-google.com
  - DOMAIN-SUFFIX,www.googleadservices.com
  - DOMAIN-SUFFIX,www.googletagservices.com
  - DOMAIN-SUFFIX,yt1.ggpht.com
  - DOMAIN-SUFFIX,yt10.ggpht.com
  - DOMAIN-SUFFIX,yt2.ggpht.com
  - DOMAIN-SUFFIX,yt2.ggpht.com
  - DOMAIN-SUFFIX,yt3.ggpht.com 
  - DOMAIN-SUFFIX,yt4.ggpht.com
  - DOMAIN-SUFFIX,yt5.ggpht.com
  - DOMAIN-SUFFIX,yt6.ggpht.com
  - DOMAIN-SUFFIX,yt7.ggpht.com
  - DOMAIN-SUFFIX,yt8.ggpht.com
  - DOMAIN-SUFFIX,yt9.ggpht.com
  - DOMAIN-SUFFIX,notifications-pa.googleapis.com
  - DOMAIN-SUFFIX,yt3.googleusercontent.com
  - DOMAIN-SUFFIX,searchnotifications-pa.googleapis.com
  - DOMAIN-SUFFIX,pubsub.googleapis.com
  - DOMAIN-SUFFIX,encrypted-tbn0.gstatic.com
  - DOMAIN-SUFFIX,encrypted-tbn1.gstatic.com
  - DOMAIN-SUFFIX,encrypted-tbn2.gstatic.com
  - DOMAIN-SUFFIX,encrypted-tbn3.gstatic.com
  - DOMAIN-SUFFIX,androidpay-users-pa.googleapis.com
  - DOMAIN-SUFFIX,federatedcompute-pa.googleapis.com
  - DOMAIN-SUFFIX,translate.googleapis.com
  - DOMAIN-SUFFIX,mtalk.google.com
  - DOMAIN-SUFFIX,taskassist-pa.googleapis.com
  - DOMAIN-SUFFIX,alt7-mtalk.google.com
  - DOMAIN-SUFFIX,geller-pa.googleapis.com
  - DOMAIN-SUFFIX,play-fe.googleapis.com
  - DOMAIN-SUFFIX,android.googleapis.com
  - DOMAIN-SUFFIX,proactivebackend-pa.googleapis.com
