payload:
- DOMAIN-SUFFIX,cloudfront.net
- DOMAIN-SUFFIX,turnerlive.warnermediacdn.com
- DOMAIN-SUFFIX,vs-hls-push-ww-live.akamaized.net
- DOMAIN-SUFFIX,b-nhkwlive-ojp.nhkworld.jp
- DOMAIN-SUFFIX,mine.nu
- DST-IP-CIDR, 60.248.77.76/32
