mixed-port: 7893
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
hosts:
 homeassistant.local: 192.168.10.9
dns:
  enable: true
  listen: :7874
  ipv6: true
  proxy-server-nameserver: [https://223.5.5.5/dns-query]
  nameserver-policy:
    "rule-set:cn_domain,private_domain,fakeipfilter_cn,steamcn_domain,microsoftcn_domain,applecn_domain":
    - https://dns.alidns.com/dns-query#disable-qtype-65=true
    - https://doh.pub/dns-query#disable-qtype-65=true
    "rule-set:fakeipfilter_!cn":
    - https://8.8.8.8/dns-query#默认代理&disable-qtype-65=true
  nameserver:
    - https://8.8.8.8/dns-query#默认代理&ecs=223.5.5.0/24
  fallback:
    - https://8.8.8.8/dns-query#默认代理
  fallback-filter:
    geoip: true
    geoip-code: CN
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-range6: fdfe:dcba:9876::1/64
  fake-ip-filter:
    - '*.lan'
    - '*.local'
profile:
  store-selected: true
  store-fake-ip: true

geox-url:
  mmdb: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb"
  
rule-providers:
  antiad: {type: http,behavior: classical,url: https://raw.githubusercontent.com/hhzol/ACL4SSR/main/Clash/config/ad.yaml,interval: 86400,path: ANTIAD.yaml}
  US: {type: http,behavior: classical,url: https://raw.githubusercontent.com/hhzol/ACL4SSR/main/Clash/config/us.yaml,interval: 86400,path: US.yaml}
  AI: {type: http,format: mrs,behavior: domain,url: https://gh-proxy.org/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-ai-!cn.mrs,path: ai.mrs,interval: 86400}
  bbc: {type: http,format: mrs,behavior: domain,url: https://gh-proxy.org/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/bbc.mrs,path: bbc.mrs,interval: 86400}
  netflix: {type: http,format: mrs,behavior: domain,url: https://gh-proxy.org/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/netflix.mrs,path: netflix.mrs,interval: 86400}
  spotify: {type: http,format: mrs,behavior: domain,url: https://gh-proxy.org/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/spotify.mrs,path: spotify.mrs,interval: 86400}
  tiktok: {type: http,format: mrs,behavior: domain,url: https://gh-proxy.org/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/tiktok.mrs,path: tiktok.mrs,interval: 86400}
  geosite-private: {type: http,format: mrs,behavior: domain,url: https://gh-proxy.org/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs,path: geosite-private.mrs,interval: 86400}
  geoip-private: {type: http,format: mrs,behavior: domain,url: https://gh-proxy.org/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosip/private.mrs,path: geoip-private.mrs,interval: 86400}
  geoip-cn: {type: http,format: mrs,behavior: domain,url: https://gh-proxy.org/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs,path: geoip-cn.mrs,interval: 86400}
  
