mixed-port: 7893
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
hosts:
 homeassistant.local: 192.168.10.9
dns:
  enable: true
  listen: :7874
  ipv6: true
  default-nameserver: [114.114.114.114, 119.29.29.29, 223.5.5.5]
  nameserver-policy:
    geosite:cn,private: [tls://dns.alidns.com,tls://dot.pub]
    rule-set:ZHILIAN: [tls://dns.alidns.com,tls://dot.pub]
  nameserver: [8.8.8.8#🐟 漏网之鱼]
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - '*.local'
    - rule-set:FAKEIPFILTER
profile:
  store-selected: true
  store-fake-ip: true
rule-providers:
   ANTIAD:
     type: http
     behavior: classical
     url: https://raw.githubusercontent.com/hhzol/ACL4SSR/main/Clash/config/ad.yaml
     interval: 86400
     path: ANTIAD.yaml
   ADBLOCK:
     type: http
     behavior: classical
     url: https://raw.githubusercontent.com/hhzol/update_adblock/main/rule_provider/adblock.yaml
     interval: 86400
     path: adblock.yaml
   ZHILIAN:
     type: http
     behavior: classical
     url: https://raw.githubusercontent.com/hhzol/ACL4SSR/main/Clash/config/cn.yaml
     interval: 86400
     path: ZHILIAN.yaml
   US:
     type: http
     behavior: classical
     url: https://raw.githubusercontent.com/hhzol/ACL4SSR/main/Clash/config/us.yaml
     interval: 86400
     path: US.yaml
   UK:
     type: http
     behavior: classical
     url: https://raw.githubusercontent.com/hhzol/ACL4SSR/main/Clash/config/uk.yaml
     interval: 86400
     path: UK.yaml
   PROXY:
     type: http
     behavior: classical
     url: https://raw.githubusercontent.com/hhzol/ACL4SSR/main/Clash/config/proxy.yaml
     interval: 86400
     path: proxy.yaml
   FAKEIPFILTER:
     type: http
     behavior: classical
     url: https://raw.githubusercontent.com/hhzol/ACL4SSR/main/Clash/config/fakeipfilter.yaml
     interval: 86400
     path: fakeipfilter.yaml

















