payload:
- DOMAIN-KEYWORD,cambridge.org
- GEOSITE,bbc
- DOMAIN-SUFFIX,bbcx-internal.com
- DOMAIN-SUFFIX,live.bidi.net.uk
- DOMAIN-SUFFIX,vod-dash-uk-live.akamaized.net
- DOMAIN-SUFFIX,vod-sub-uk-live.akamaized.net
