payload:
- DOMAIN-KEYWORD,cambridge.org
- DOMAIN-SUFFIX,error-report.com
- DOMAIN-SUFFIX,geolocation.onetrust.com
#- DOMAIN-SUFFIX,cdn.cookielaw.org
#- DOMAIN-SUFFIX,polarbyte.com
- DOMAIN-SUFFIX,www.googletagmanager.com
#- DOMAIN-SUFFIX,html-load.com
#- DOMAIN-SUFFIX,content-loader.com
#- DOMAIN-SUFFIX,static.hotjar.com
- GEOSITE,bbc
- DOMAIN-SUFFIX,bbcx-internal.com
- DOMAIN-SUFFIX,live.bidi.net.uk
- DOMAIN-SUFFIX,vod-dash-uk-live.akamaized.net
- DOMAIN-SUFFIX,vod-sub-uk-live.akamaized.net
